# This is the completed azure-pipelines.yaml file from previous steps.

variables:
  ConnectedServiceName: 'shuvomoybasak'

  WebAppName: 'shuvomoybasak-flaskpipelines'

trigger:

- master
pool:

  name: Hosted Ubuntu 1604

steps:

- task: UsePythonVersion@0

  inputs:

    versionSpec: '3.6'

    architecture: 'x64'

- script: |

    python3.6 -m venv antenv3.6

    source antenv3.6/bin/activate

    pip3.6 install setuptools

    pip3.6 install -r requirements.txt



  # The displayName is shows in the pipeline UI when a build runs

  displayName: 'Install Dependencies'



- task: ArchiveFiles@2

  inputs:

    rootFolderOrFile: '$(Build.SourcesDirectory)'

    includeRootFolder: false

    archiveType: 'zip'

    archiveFile: '$(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip'

    replaceExistingArchive: true

    verbose: # Optional


    # The following command is specific to the python-sample-vscode-flask-tutorial code.

    # You may or may not need a startup command for your own app.



   # StartupCommand: 'gunicorn --bind=0.0.0.0 --workers=4 startup:app'
